name: "✨ Feature Request"
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to improve Incial? We'd love to hear it.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief summary of the feature you'd like.
      placeholder: What should this feature do?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this solve? Why is it needed?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you think this should work.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered.

  - type: textarea
    id: design
    attributes:
      label: Design / Figma Reference
      description: Link to any Figma frames, mockups, or screenshots.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - "P0 - Blocker"
        - "P1 - Core"
        - "P2 - Secondary"
        - "P3 - Polish"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, links, or references.
